# Build settings

markdown: kramdown
#permalink: /:title.html
# paginate: 6
# paginate_path: "/CN/archive/page:num"

port: 8000

sass:
  sass_dir: assets/css
  style: :nested
 

fill_default_content: true

#gems: ["jekyll-paginate"]

gems: [jekyll-paginate, jekyll-gist, jekyll-polyglot]

blog:
    tags:
        url: /blog/tags/
        title_prefix: "blog - tag: "
        layout: tag.html
        
        
####Polyglot

markdown:         redcarpet
highlighter:      pygments
about:
  en: About us
  zh_CN: 关于我们  

work:
  en: Inspirational people and projects
  zh_CN: 鼓舞人心的人和事
  
post:
  en: Blog
  zh_CN: 闲话

contact:
  en: Contact
  zh_CN: 联系我们  

home:
  en: Home
  zh_CN: 主页
  
archive: 
  en: archive
  zh_CN: 存档
  
title: 
  en: Newbies in Kiwi Land
  zh_CN: 新来乍到新西兰 

description: 
  en: traveller // thinker// helper
  zh_CN: 旅行者 // 思考者// 支持者

blurb: 
  en: <p><strong> We are Ralf and Jing, a Dutch-Chinese couple. We like adventure and outdoor stuff. Apart from entertaining ourselves, we also try our best to be useful. We like to share ideas, thoughts
      and <a href="http://s1071.photobucket.com/">beautiful things</a> in life with you. </p>
  zh_CN: <p><strong> 我们是 Ralf 和 Jing, 一对荷兰中国的夫妻. 我们喜欢冒险和户外活动。 除了开开心心得活着, 我们尽力做有用的人. 我们喜欢和您分享新鲜的主意，想法，
      以及生活中的一些<a href="http://s1071.photobucket.com/">美丽的事务</a>。</p>

post_title:
   en: Nonsense about travel, adventure, sports and nonsense
   zh_CN: 关于旅行， 冒险，运动以及胡言乱语的瞎扯

  
email: zouzoujing@gmail.com

# Permalinks
permalink: pretty

include: ['_pages']
exclude: ['LICENSE.md', 'README.md', 'publi.sh']
# Setup
#title:            Polyglot
tagline:          'Straightforward I18n for Jekyll Blogs'

#url:              https://untra.github.com/polyglot
#baseurl:          /

paginate: 5
# Custom vars
version:          1.1.0

#github:
 # repo:           https://github.com/untra/polyglot

#Polyglot
languages: ["en", "zh_CN"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
data_dir: ./_data

#### Polyglot