# Build settings

markdown: kramdown
permalink: pretty
paginate: 6
paginate_path: "/CN/archive/page:num"

port: 8000

sass:
  sass_dir: assets/css
  style: :nested
 
 # Multiple languages
languages:          ['en', 'cn']

# If not config, the first of languages will be the default
language_default:   'en'

fill_default_content: true
