#-------------------------------
# General Site Settings

logo: 'logo.svg'
background-image: 'hero-bg.jpg'


lan:
- {name: English, url: 'index.html'}
- {name: 中文, url: 'index.html'}

menu:
- {name: About us, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}


navbar:
- {name: Home, url: 'index.html'}
- {name: About us, url: 'index.html/ #about-me'}
- {name: Archive, url: '/english/archive/index.html'}
- {name: Contact, url: '#contact'}



#-------------------------------
# About Section

avatar: 'ralfjing.jpg'

#-------------------------------
# Work Section

projects:
- {name: Matthieu Ricard, link: 'http://www.matthieuricard.org/en', folder: 'proj-1'}
- {name: Alan Watts, link: 'http://alanwatts.com/mark/alanwatts.com/OLD/index.html', folder: 'proj-2'}
- {name: Room to Read, link: 'www.roomtoread.org/', folder: 'proj-3'}
- {name: Hometown Education, link: 'http://www.hometowneducation.org/', folder: 'proj-4'}
- {name: Billions in Change,  link: 'http://billionsinchange.com/', folder: 'proj-5'}
- {name: Dev tips,  link: 'https://www.youtube.com/channel/UCyIe-61Y8C4_o-zZCtO4ETQ', folder: 'proj-6'}
- {name: Effective Altruism, link: 'http://www.effectivealtruism.org/', folder: 'proj-7'}
- {name: 350.org, link: 'https://350.org/', folder: 'proj-8'}


social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}