#-------------------------------
# General Site Settings

title: 环游世界
description: 旅行着 // 思考着// 漂流着
email: artist@email


logo: 'logo.svg'
background-image: 'hero-bg.jpg'


lan:
- {name: English, url: '/EN/index.html'}
- {name: 中文, url: '/CN/index.html'}

menu:
- {name: 关于我们, url: '#about-me'}
- {name: 工作, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}


navbar:
- {name: 主页, url: '/CN/index.html'}
- {name: 关于我们, url: '/CN/index.html/ #work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}



#-------------------------------
# About Section

avatar: 'travitar.jpg'


blurb: <p><strong>我是一个狼 <a href="http://travisneilson.com">digital interfaces</a>, but he also puts effort into crafting <a href="http://soundcloud.com/travis-neilson">next-level beats</a> and <a href="http://youtube.com/user/devtipsfordesigners">YouTube videos</a> about making codes happen.</p>





#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1'}
- {name: City-IN website concept, folder: 'proj-2'}
- {name: Crispy Icons, folder: 'proj-3'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4'}
- {name: Fresh It Up, folder: 'proj-5'}
- {name: Timeline Page, folder: 'proj-6'}
- {name: Weather Dashboard, folder: 'proj-7'}
- {name: Stripes & Co, folder: 'proj-8'}




